# Generated by Django 2.2.5 on 2019-09-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20190922_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Strains',
            new_name='Strain',
        ),
    ]
