# Generated by Django 2.2.5 on 2019-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20190923_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='updated',
        ),
        migrations.AlterField(
            model_name='strain',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
