# Generated by Django 2.2.5 on 2019-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_strain_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='strain_effect_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_flavor_list',
            field=models.TextField(blank=True),
        ),
    ]
